import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import { useCookies } from "react-cookie"
import Login from '@/component/Login/login'
import AlertBox from "@/component/Alert/alert";
import Navbar from '@/component/Navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ materials }) {
  const [loggedin, setLoggedin] = useState(false);
  const [cookie, setCookie] = useCookies(["user"]);
  useEffect(() => {
    if (cookie.user != null) {
      setLoggedin(true);
    }
  })

  return (
    <>
      <Head>
        <title>Inventory Management IOCL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loggedin ? <div>
        <div style={{ backgroundColor: "#FFF", height: "100vh" }}>
          <Navbar />
          <div style={{ marginLeft: "360px" }}>
            <AlertBox materials={materials} />
          </div>
        </div>
      </div> : <Login setLoggedin={setLoggedin} />}
    </>
  )
}

export async function getServerSideProps({ query, req }) {
  let materials;
  try {
    var requestOptions = {
      method: 'GET',
      redirect: 'follow'
    };

    const response = await fetch("http://localhost:3001/materials/", requestOptions);
    const jsonResponse = await response.json();
    materials = jsonResponse;
  } catch (err) {
    console.log(err);
    return {
      redirect: {
        destination: "/404",
        permanent: false,
      }
    }
  }
  return {
    props: {
      materials
    },
  };
}
